### ISSUE TITLE
Bug ImportError: cannot import name 'dist'

### ISSUE THREAD

**Issue by alvaromerinog** [alvaromerinog/wsl_install_script#16]
Sometimes the following message is showed while trying to use Python 3.7 after the installation:

```bash
ImportError: cannot import name 'dist'
```

This problem can be solved executing the following instruction in the terminal:

```bash
sudo apt install python3.7-distutils
```

**To add this instruction to the script.**

**Comment by fernandom06** [comment]
fix in https://github.com/alvaromerinog/wsl_install_script/pull/19 we can close this issue
